### ISSUE TITLE
View with source annotation display does not load

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#21]
One of the views for #20 does not load; it fails with: (on current MoBIE-beta)
```
Exception in thread "Thread-12" java.lang.NullPointerException
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.lambda$createAnnotatedMasks$0(AnnotatedMaskCreator.java:43)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.createAnnotatedMasks(AnnotatedMaskCreator.java:43)
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.<init>(AnnotatedMaskCreator.java:30)
	at org.embl.mobie.viewer.MoBIE.loadAnnotatedMaskTables(MoBIE.java:678)
	at org.embl.mobie.viewer.view.ViewManager.showAnnotatedMaskDisplay(ViewManager.java:399)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:356)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:268)
	at org.embl.mobie.viewer.ui.UserInterfaceHelpers.lambda$null$7(UserInterfaceHelpers.java:493)
	at java.lang.Thread.run(Thread.java:748)
```
The project metadata should be valid (at least it's valid according to our jsonschema).
To reproduce: https://github.com/mobie/clem-example-project, branch: `more-views`, view: `paper->Fig2_a`.

**Comment by constantinpape** [comment]
My first suspission: we have a `sourceAnnotationDisplay` with multiple sources per "annotationRegion" (we really need to rename it to region, that makes so much more sence) and this is creating some issues.

**Comment by tischi** [comment]
I am sitting at the gate at may soon be out of internet.
I will thus post intermediate findings:

It cannot find the source: "em-detail-a1".

**Comment by constantinpape** [comment]
ok, thanks for checking! I will investigate later.

**Comment by constantinpape** [comment]
Thanks that was the issue.
